<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520115310 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE acknowledgement (id UUID NOT NULL, status VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE acknowledgement_detail (id UUID NOT NULL, level VARCHAR(255) NOT NULL, item VARCHAR(255) NOT NULL, reason_code VARCHAR(255) NOT NULL, reason_message VARCHAR(255) NOT NULL, acknowledgement_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B144431333DAB9B ON acknowledgement_detail (acknowledgement_id)');
        $this->addSql('CREATE TABLE address_read (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, address_line1 VARCHAR(255) NOT NULL, address_line2 VARCHAR(255) NOT NULL, address_line3 VARCHAR(255) NOT NULL, postal_code VARCHAR(5) NOT NULL, country_subdivision VARCHAR(255) NOT NULL, locality VARCHAR(100) NOT NULL, country_code VARCHAR(2) NOT NULL, country_name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE b2g_additional_data (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pm BOOLEAN NOT NULL, pm_only BOOLEAN NOT NULL, manages_payment_status BOOLEAN NOT NULL, manages_legal_commitment_code BOOLEAN NOT NULL, manages_legal_commitment_or_service_code BOOLEAN NOT NULL, service_code_status BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE facility_payload_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, id_instance INT NOT NULL, siret VARCHAR(14) NOT NULL, siren VARCHAR(9) NOT NULL, name VARCHAR(100) NOT NULL, facility_type VARCHAR(255) NOT NULL, diffusible VARCHAR(255) NOT NULL, administrative_status VARCHAR(255) NOT NULL, version INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, address_id INT NOT NULL, b2g_additional_data_id INT NOT NULL, legal_unit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F06F81BEF5B7AF75 ON facility_payload_history (address_id)');
        $this->addSql('CREATE INDEX IDX_F06F81BE7EB155CA ON facility_payload_history (b2g_additional_data_id)');
        $this->addSql('CREATE INDEX IDX_F06F81BE3F86EE63 ON facility_payload_history (legal_unit_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_instance_version ON facility_payload_history (id_instance, version)');
        $this->addSql('CREATE TABLE flow (flow_id UUID NOT NULL, submitted_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, tracking_id TEXT NOT NULL, flow_type VARCHAR(255) NOT NULL, processing_rule VARCHAR(255) NOT NULL, processing_rule_source VARCHAR(255) NOT NULL, flow_direction VARCHAR(255) NOT NULL, flow_syntax VARCHAR(255) NOT NULL, flow_profile VARCHAR(255) NOT NULL, file_sha256 VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, acknowledgement_id UUID NOT NULL, issued_by_id UUID NOT NULL, PRIMARY KEY (flow_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_52C0D67033DAB9B ON flow (acknowledgement_id)');
        $this->addSql('CREATE INDEX IDX_52C0D670784BB717 ON flow (issued_by_id)');
        $this->addSql('CREATE TABLE legal_unit_payload_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, id_instance INT NOT NULL, siren VARCHAR(9) NOT NULL, business_name VARCHAR(255) NOT NULL, entity_type VARCHAR(255) NOT NULL, administrative_status VARCHAR(255) NOT NULL, version INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQUE_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE acknowledgement_detail ADD CONSTRAINT FK_B144431333DAB9B FOREIGN KEY (acknowledgement_id) REFERENCES acknowledgement (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE facility_payload_history ADD CONSTRAINT FK_F06F81BEF5B7AF75 FOREIGN KEY (address_id) REFERENCES address_read (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE facility_payload_history ADD CONSTRAINT FK_F06F81BE7EB155CA FOREIGN KEY (b2g_additional_data_id) REFERENCES b2g_additional_data (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE facility_payload_history ADD CONSTRAINT FK_F06F81BE3F86EE63 FOREIGN KEY (legal_unit_id) REFERENCES legal_unit_payload_history (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE flow ADD CONSTRAINT FK_52C0D67033DAB9B FOREIGN KEY (acknowledgement_id) REFERENCES acknowledgement (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE flow ADD CONSTRAINT FK_52C0D670784BB717 FOREIGN KEY (issued_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE acknowledgement_detail DROP CONSTRAINT FK_B144431333DAB9B');
        $this->addSql('ALTER TABLE facility_payload_history DROP CONSTRAINT FK_F06F81BEF5B7AF75');
        $this->addSql('ALTER TABLE facility_payload_history DROP CONSTRAINT FK_F06F81BE7EB155CA');
        $this->addSql('ALTER TABLE facility_payload_history DROP CONSTRAINT FK_F06F81BE3F86EE63');
        $this->addSql('ALTER TABLE flow DROP CONSTRAINT FK_52C0D67033DAB9B');
        $this->addSql('ALTER TABLE flow DROP CONSTRAINT FK_52C0D670784BB717');
        $this->addSql('DROP TABLE acknowledgement');
        $this->addSql('DROP TABLE acknowledgement_detail');
        $this->addSql('DROP TABLE address_read');
        $this->addSql('DROP TABLE b2g_additional_data');
        $this->addSql('DROP TABLE facility_payload_history');
        $this->addSql('DROP TABLE flow');
        $this->addSql('DROP TABLE legal_unit_payload_history');
        $this->addSql('DROP TABLE "user"');
    }
}
